apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pet-owner
  name: pet-owner
  namespace: pet-owner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet-owner
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pet-owner
    spec:
      containers:
      - image: ayadinou/tp_devops_spring_boot_app:2.7.4-69
        name: pet_owner
        imagePullPolicy: IfNotPresent
        env:
          - name: DATABASE_HOST
            value: "mysqldb-service.mysql.svc.cluster.local"
          - name: DATABASE_USER
            value: "ayadinou"
          - name: DATABASE_PASSWORD
            value: "ayadinou1601"
          - name: DATABASE_ROOT_PASSWORD
            value: "ayainou1601"
          - name: DATABASE_NAME
            value: "pet_store"
          - name: DATABASE_PORT
            value: "3306"
        ports:
          - containerPort: 8080
