apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-10-24T14:19:10Z"
  generation: 1
  labels:
    app: petowner-deployment
  name: petowner-deployment
  namespace: default
  resourceVersion: "2354"
  uid: d6ce3984-aa77-41a9-96a1-e4dbb7151413
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: petowner-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: petowner-deployment
    spec:
      containers:
      - image: ayadinou/tp_devops_spring_boot_app:1.0.0
        imagePullPolicy: IfNotPresent
        name: tp-devops-spring-boot-app-rvdw2
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
