apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb-deployment
  namespace: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
        - name: mysqldb
          image: mysql
          env:
            - name: MYSQL_USER
              value: "ayadinou"
            - name: MYSQL_PASSWORD
              value: "ayadinou"
            - name: MYSQL_ROOT_PASSWORD
              value: "ayadinou"
            - name: MYSQL_DATABASE
              value: "pet_store"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          emptyDir: {}
