apiVersion: v1
kind: Service
metadata:
  name: mysqldb-service
  namespace: mysql
spec:
  type: LoadBalancer
  selector:
    app: mysqldb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
