apiVersion: v1
kind: Service
metadata:
  name: pet-service
  namespace: pet-owner
spec:
  type: LoadBalancer
  selector:
    app: pet-owner
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

